name: Release

on:
  workflow_dispatch:
    inputs:
      build-tag:
        description: 'Tag for the build artifacts'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image to DOCR
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCR_REGISTRY_URL }}/facility-hub:${{ github.event.inputs.build-tag }} .
        
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to DOCR
        run: echo "${{ secrets.DOCR_TOKEN }}" | docker login ${{ secrets.DOCR_REGISTRY_URL }} -u _token --password-stdin

      - name: Push Docker image to DOCR
        run: docker push ${{ secrets.DOCR_REGISTRY_URL }}/facility-hub:${{ github.event.inputs.build-tag }}
        
        env:
          DOCKER_CLI_ACI: 1
